name: Run tests
on: [push]
jobs:
  e2e-test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
          ./bootstrap.sh
  run-rspec-tests:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          # Not needed with a .ruby-version file
          ruby-version: 2.7
          bundler-cache: true
      - name: Run tests
        run: |
          bundle exec rspec
